# Generated by Django 4.0.4 on 2022-05-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0003_geeksmodel_remove_aluno_turma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='resultado_final',
            field=models.CharField(default='Influência', max_length=50),
            preserve_default=False,
        ),
    ]
