# Generated by Django 3.2.3 on 2022-06-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0004_resultado_resultado_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=32, unique=True, verbose_name='http://questbiopark.pythonanywhere.com/')),
                ('expires', models.DateTimeField(verbose_name='Expires')),
            ],
        ),
    ]
