# Generated by Django 3.2.3 on 2022-06-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0006_alter_tempurl_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='url_hash',
            field=models.CharField(max_length=32, unique=True, verbose_name='https://questbiopark.pythonanywhere.com/test/123'),
        ),
    ]
