# Generated by Django 3.2.3 on 2022-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0007_alter_tempurl_url_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='instituicao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
