# Generated by Django 3.2.3 on 2022-07-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0008_resultado_instituicao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUrl',
        ),
    ]
