# Generated by Django 3.2.3 on 2022-07-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0009_delete_tempurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='instituicao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
